/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wrss1;

/**
 *
 * @author Juan Cedrick Lopez
 */
public class CREATEACCCUSTOMERS extends javax.swing.JFrame {

    /**
     * Creates new form CUSTOMERINFO
     */
    public CREATEACCCUSTOMERS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtcreateaccountforcustomers = new javax.swing.JLabel();
        txtusernameforcustomers = new javax.swing.JLabel();
        txtcreatepasswordforcustomers = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        buttoncreateforcustomers = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcreateaccountforcustomers.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        txtcreateaccountforcustomers.setText("Create Account For Customers");
        getContentPane().add(txtcreateaccountforcustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        txtusernameforcustomers.setBackground(new java.awt.Color(255, 255, 255));
        txtusernameforcustomers.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtusernameforcustomers.setText("UserName:");
        getContentPane().add(txtusernameforcustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtcreatepasswordforcustomers.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtcreatepasswordforcustomers.setText("Create Password");
        getContentPane().add(txtcreatepasswordforcustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 210, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        buttoncreateforcustomers.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        buttoncreateforcustomers.setLabel("Create");
        buttoncreateforcustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncreateforcustomersActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncreateforcustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Cedrick Lopez\\Documents\\WRSS\\Wrss1\\5555.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncreateforcustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncreateforcustomersActionPerformed
     FRONT frontFrame = new FRONT();
    this.setVisible(false);
    frontFrame.setVisible(true);
    }//GEN-LAST:event_buttoncreateforcustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATEACCCUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATEACCCUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATEACCCUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATEACCCUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREATEACCCUSTOMERS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttoncreateforcustomers;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtcreateaccountforcustomers;
    private javax.swing.JLabel txtcreatepasswordforcustomers;
    private javax.swing.JLabel txtusernameforcustomers;
    // End of variables declaration//GEN-END:variables
}
