/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wrss1;

/**
 *
 * @author Juan Cedrick Lopez
 */
public class CREATEACCADMIN extends javax.swing.JFrame {

    /**
     * Creates new form Frontpage
     */
    public CREATEACCADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtcreateaccountforadmin = new javax.swing.JLabel();
        txtusernameforadmin = new javax.swing.JLabel();
        txtcreatepasswordforadmin = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        button1createforadmin = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, -1, 419));

        txtcreateaccountforadmin.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        txtcreateaccountforadmin.setText("Create Account For Admin");
        getContentPane().add(txtcreateaccountforadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        txtusernameforadmin.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtusernameforadmin.setText("UserName:");
        getContentPane().add(txtusernameforadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtcreatepasswordforadmin.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtcreatepasswordforadmin.setText("Create Password:");
        getContentPane().add(txtcreatepasswordforadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, -1));

        button1createforadmin.setActionCommand("Create");
        button1createforadmin.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        button1createforadmin.setLabel("Create");
        button1createforadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1createforadminActionPerformed(evt);
            }
        });
        getContentPane().add(button1createforadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Cedrick Lopez\\Documents\\WRSS\\Wrss1\\5555.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1createforadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1createforadminActionPerformed
    FRONT frontFrame = new FRONT();
    this.setVisible(false);
    frontFrame.setVisible(true);
    }//GEN-LAST:event_button1createforadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATEACCADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATEACCADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATEACCADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATEACCADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CREATEACCADMIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1createforadmin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtcreateaccountforadmin;
    private javax.swing.JLabel txtcreatepasswordforadmin;
    private javax.swing.JLabel txtusernameforadmin;
    // End of variables declaration//GEN-END:variables
}
