/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wrss1;

/**
 *
 * @author Juan Cedrick Lopez
 */
public class FRONT extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public FRONT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtjbj2begwaterrefillingsalessystem = new javax.swing.JLabel();
        txtusernameforfront = new javax.swing.JLabel();
        txtpasswordforfront = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        buttonloginforfront = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        buttoncreateaccountforcustomersfront = new java.awt.Button();
        button3createaccountbuttonfront = new java.awt.Button();
        buttonloginforfront1 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtjbj2begwaterrefillingsalessystem.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        txtjbj2begwaterrefillingsalessystem.setForeground(new java.awt.Color(255, 255, 255));
        txtjbj2begwaterrefillingsalessystem.setText("  JBJ 2BEG REFILLING SALES SYSTEM");
        getContentPane().add(txtjbj2begwaterrefillingsalessystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 510, 50));

        txtusernameforfront.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtusernameforfront.setText("UserName:");
        getContentPane().add(txtusernameforfront, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        txtpasswordforfront.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        txtpasswordforfront.setText("Password:");
        getContentPane().add(txtpasswordforfront, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, -1));

        buttonloginforfront.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonloginforfront.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        buttonloginforfront.setLabel("Login as customer");
        buttonloginforfront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginforfrontActionPerformed(evt);
            }
        });
        getContentPane().add(buttonloginforfront, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, -1));
        buttonloginforfront.getAccessibleContext().setAccessibleName("Login as customer");

        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 160, -1));

        buttoncreateaccountforcustomersfront.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        buttoncreateaccountforcustomersfront.setLabel("Create Account For Customers");
        buttoncreateaccountforcustomersfront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncreateaccountforcustomersfrontActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncreateaccountforcustomersfront, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 220, -1));

        button3createaccountbuttonfront.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        button3createaccountbuttonfront.setLabel("Create Account For Admin");
        button3createaccountbuttonfront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3createaccountbuttonfrontActionPerformed(evt);
            }
        });
        getContentPane().add(button3createaccountbuttonfront, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 220, -1));

        buttonloginforfront1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        buttonloginforfront1.setLabel("Login as admin");
        buttonloginforfront1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginforfront1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonloginforfront1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Cedrick Lopez\\Documents\\WRSS\\Wrss1\\frontpage.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonloginforfrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginforfrontActionPerformed

    CONTAINERTYPE containerFrame = new CONTAINERTYPE();
    this.setVisible(false);
    containerFrame.setVisible(true);
    }//GEN-LAST:event_buttonloginforfrontActionPerformed

    private void button3createaccountbuttonfrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3createaccountbuttonfrontActionPerformed
    CREATEACCADMIN createAccAdminFrame = new CREATEACCADMIN();
    this.dispose();
    createAccAdminFrame.setVisible(true);
    }//GEN-LAST:event_button3createaccountbuttonfrontActionPerformed

    private void buttoncreateaccountforcustomersfrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncreateaccountforcustomersfrontActionPerformed
    CREATEACCCUSTOMERS createAccCustomersFrame = new CREATEACCCUSTOMERS();
    this.dispose();
    createAccCustomersFrame.setVisible(true);
    }//GEN-LAST:event_buttoncreateaccountforcustomersfrontActionPerformed

    private void buttonloginforfront1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginforfront1ActionPerformed
    ADMINSYSTEM adminSystem = new ADMINSYSTEM();
    adminSystem.setVisible(true);
    this.setVisible(false); 
    }//GEN-LAST:event_buttonloginforfront1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRONT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRONT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRONT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRONT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRONT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button3createaccountbuttonfront;
    private java.awt.Button buttoncreateaccountforcustomersfront;
    private java.awt.Button buttonloginforfront;
    private java.awt.Button buttonloginforfront1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtjbj2begwaterrefillingsalessystem;
    private javax.swing.JLabel txtpasswordforfront;
    private javax.swing.JLabel txtusernameforfront;
    // End of variables declaration//GEN-END:variables
}
